apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-collector
      port: 14268
      protocol: TCP
      targetPort: 14268
  selector:
    app: jaeger

